include the routing module
anvilistas/anvil-extras pull request #32
Opened 2021-03-13 04:13 UTC by s-cork

2021-03-13 04:22 UTC, s-cork commented
can we change the max line length for black - i really don't like 79... I personally prefer 119.

2021-03-13 09:12 UTC, meatballs commented
Black uses 88 https://black.readthedocs.io/en/stable/the_black_code_style.html

On March 13, 2021 4:22:17 AM UTC, stu ***@***.***> wrote:
>can we change the max line length for black - i really don't like 79...
>I personally prefer 119.

-- 
Owen Campbell 

This email has been digitally signed. 
For further information visit http://owencampbell.me.uk/pgp

2021-03-16 08:57 UTC, s-cork commented
I'll make the docs a separate pr I think.
Let me know if there's anything you want changing in the code or questions.

2021-03-16 09:01 UTC, meatballs requested changes

2021-03-16 09:01 UTC, meatballs commented on client_code/routing/_navigation.py
> +from time import sleep
Licence text here too

2021-03-16 09:01 UTC, meatballs commented on client_code/routing/_routing.py
> +from collections import namedtuple as _namedtuple
licence text here too

2021-03-16 09:01 UTC, meatballs commented on client_code/routing/_session_expired.py
> +from anvil.js.window import jQuery as _S
licence text

2021-03-16 09:28 UTC, meatballs commented
Let me push a fix for the github action. I hit this yesterday on another repo and forgot it would apply here too.

2021-03-16 09:30 UTC, meatballs approved these changes

2021-03-16 09:31 UTC, merged

2021-03-16 09:32 UTC, meatballs commented
Nice! That's a big step forward for this repo!