multi select component
anvilistas/anvil-extras pull request #44
Opened 2021-04-19 13:58 UTC by s-cork

- [x] multi select functionality
- [x] demo
- [ ] docs

2021-04-19 14:12 UTC, s-cork commented
@meatballs - do you think it's worth refactoring the `add_script` into its own separate util function? 

Any initial thoughts before I add the docs let me know.

2021-04-19 17:13 UTC, meatballs commented
I'll try to have a look at this tomorrow

2021-04-22 08:20 UTC, meatballs commented
Sorry it took me a while, but I've tried that out now and it's looking great. Nice work!

2021-04-22 08:34 UTC, s-cork commented
Never any rush! great I'll have a go at documentation. And will mark it as ready for review when that's done. 
Will also add the change event in the demo

2021-04-26 07:23 UTC, s-cork commented
I think this might be a better library to use https://developer.snapappointments.com/bootstrap-select/examples/

2021-04-26 08:39 UTC, meatballs commented
> I think this might be a better library to use https://developer.snapappointments.com/bootstrap-select/examples/

Yeah, that does look nice.

2021-04-26 08:55 UTC, s-cork commented
And it still supports bootstrap 3 which is a win

2021-05-18 16:00 UTC, s-cork commented
There's a small bug - I think it conflicts with anvil's version so just need to check it works properly

2021-05-19 15:02 UTC, meatballs requested changes
Just a couple of minor things from me. Looking good!

2021-05-19 15:02 UTC, meatballs commented on client_code/MultiSelectDropDown/__init__.py
> +        value = item.get("value", sentinal)
spelling: s/sentinal/sentinel

2021-05-19 15:19 UTC, s-cork commented on client_code/MultiSelectDropDown/__init__.py
> +                options.append(option)
good idea - this would be a great function for singledispatch. When i get round to adding that to functools remind me and ill re-refactor.

2021-05-20 08:48 UTC, meatballs approved these changes

2021-05-20 08:48 UTC, merged